---

- name: Config tasks
  become: true
  tags:
    - logrotate_config
    - logrotate
  block:

    - name: Manage logrotate config file
      ansible.builtin.template:
        src: logrotate.conf.j2
        dest: "{{ logrotate_global_config_file }}"
        owner: root
        group: root
        mode: 0644
      when: logrotate_global_config_options is defined and logrotate_global_config_options

    - name: Dropin tasks
      ansible.builtin.include_tasks: dropin.yml
      when: logrotate_dropin_config_options is defined and logrotate_dropin_config_options
